### ISSUE TITLE
Installation doc curl location url for Focal image: 404

### ISSUE THREAD

**Issue by kcalmond** [raspbernetes/docs#42]
# Details

**What steps did you take and what happened:**

This link doesn't work anymore: http://cdimage.ubuntu.com/releases/focal/release/ubuntu-20.04.1-preinstalled-server-arm64+raspi.img.xz

**Anything else you would like to add:**

Looks like you need to just change it to this: http://cdimage.ubuntu.com/releases/focal/release/ubuntu-20.04.2-preinstalled-server-arm64+raspi.img.xz

**Comment by xUnholy** [comment]
Thanks for raising this issue @kcalmond - PRs are also very welcome if you're interested
